container:
  image: cirrusci/android-sdk:28
  cpu: 4
  memory: 8G

task:
  name: Build release apk

  environment:
    KEYSTORE: ENCRYPTED[360cfee3ec21324505dfeb107e8d02f2deae4c183350a2e123d842d760ee029e3d0df07037fd9b48ee27da93e838af4a]
    KEYSTORE_PASSWORD: ENCRYPTED[32f8844539096e84050656f57f4b35405be5b53641a8f6697aed45f8f049e838ca145c30fe74d6f3b87395c56020a1a7]

  build_release_apk_script: |
    ./gradlew assembleRelease

  build_apksigner_script: |
    cd ../
    git clone https://github.com/fornwall/apksigner
    cd apksigner
    ./gradlew
    cp ./build/libs/apksigner-all.jar /tmp/apksigner.jar

  sign_release_apk_script: |
    echo "$KEYSTORE" | base64 -d > keystore.jks
    java -jar /tmp/apksigner.jar -p "$KEYSTORE_PASSWORD" keystore.jks \
      ./app/build/outputs/apk/release/app-release-unsigned.apk \
      ./termux-tasker-release-g${CIRRUS_CHANGE_IN_REPO:0:8}.apk

  release_artifacts:
    path: "./*.apk"

  unsigned_artifacts:
    path: "./app/build/outputs/apk/release/*.apk"
